### ISSUE TITLE
Contact form not properly working with ID based Formspree form

### ISSUE THREAD

**Issue by ajralph** [raviriley/agency-jekyll-theme-starter#1]
Hey there,
I am using this for my homepage and wanted to configure the contact form.
I created a form with Formspree and wanted to use ID-based forms.

1. When I add my f/<form_id> as `formspree_form_path` in `_config.yml`, the contact form still uses the configured `email` instead of ID.
2. I tried to work around this by configuring the Formspree ID as my email in `_config.yml`. Now it uses the correct `action` URL and I receive the messages via Formspree. However, the user still gets the error message _Sorry <name>, it seems that my mail server is not responding. Please try again later! _ .

Am I doing something wrong? I'd be happy to submit a pull request if I know what to look for.

Thanks.

Best regards
Ralph

**Comment by raviriley** [comment]
Good catch! Looks like I forgot to add the `formspree_form_path: "f/a_form_id"` to this repo's `config.yml`.

**Comment by raviriley** [comment]
If you add `formspree_form_path: "f/a_form_id"` to your config.yml everything should work as expected.

**Comment by ajralph** [comment]
Hi, thanks for the quick reply.
However, as I mentioned in the original post, I have `formspree_form_path` configured (there was a template for it in my `_config.yml` that I just needed to uncomment).
Unfortunately, it still doesn't properly work.

If I comment out `email` and only provide a `formspree_form_path`, the contact form uses `action="https://formspree.io/"` and fails to insert the formspree id.

Any thoughts?

**Comment by raviriley** [comment]
Oh I see, that's odd. Everything works as intended for me when I test it. Can you make sure you are using the correct form ID, and that everything is up to date? Run `bundle update` and test your form locally. If it works locally but doesn't work when published, you can narrow down the cause of the issue.

**Comment by raviriley** [comment]
Closing stale issue, feel free to reopen with an update
