### ISSUE TITLE
Add academicons

### ISSUE THREAD

**Issue by aosavi** [raviriley/agency-jekyll-theme-starter#10]
I'd like to add [academicons](https://jpswalsh.github.io/academicons/) to the template and need to change head.html for that. What's the best way to proceed? Can I create a new head.html, add the line for the academicons, and somehow link to your agency repo for everything else in the head.html?

Thank you providing this starter template in the first place!

**Comment by raviriley** [comment]
Yes, that's definitely doable! 

You'll need to override the theme's `head.html` file, which you can find [here](https://github.com/raviriley/agency-jekyll-theme/blob/master/_includes/head.html). 
In your repo, create the `_includes` folder and create `head.html` inside of it. Then, I would suggest copying the contents of [this](https://github.com/raviriley/agency-jekyll-theme/blob/master/_includes/head.html) file into `head.html` and adding whatever lines of code you need to add academicons support. 

Let me know if you have any more questions!

**Comment by raviriley** [comment]
Feel free to reopen this if you have more questions.
