### ISSUE TITLE
Whitespace in contact form (message field)

### ISSUE THREAD

**Issue by aosavi** [raviriley/agency-jekyll-theme-starter#11]
When I open the theme, the message field in the contact form is already pre-filled with about a dozen spaces. This way, the cursor blinks halfway the message field and the field tip ("Message*") is hidden. I've only run the theme locally thus far.

**Comment by raviriley** [comment]
Should be fixed by PR [#61](https://github.com/raviriley/agency-jekyll-theme/pull/61). @aosavi are you still experiencing this issue?

**Comment by aosavi** [comment]
@raviriley, for some reason I am. I'm using the starter, which relies on the fixed repo if I understand correctly (and not using my own contact.html). Tried to reload without cache, but no luck. Does it require some time to propagate?

**Comment by raviriley** [comment]
@aosavi You have to re-build/deploy your repo for the fix to appear. For this repo, the latest commit triggered a build and deploy to GitHub Pages, and once that was done the fix appeared.

**Comment by aosavi** [comment]
@raviriley Thanks, that's good to know. I'm not sure how to do that though. Could you tell me, or is there documentation that I can use to find out? I've generated a website from your repo once and never rebuild it. Is that necessary for updates to be applied? Thanks!

**Comment by raviriley** [comment]
@aosavi if you have your repo set up with GitHub Pages, simply push anything to the repo and it will re-deploy.

**Comment by raviriley** [comment]
For example I added a space to the README to trigger a deployment for this repo: https://github.com/raviriley/agency-jekyll-theme-starter/commit/72f949fc00bc58f8e79dd771510bcd1278f72c2e

**Comment by aosavi** [comment]
Brilliant, it worked! Thanks for creating and maintaining this great theme.

**Comment by raviriley** [comment]
@aosavi great! Thanks for the kind words :)
