### ISSUE TITLE
Add attributes to links in team section

### ISSUE THREAD

**Issue by aosavi** [raviriley/agency-jekyll-theme-starter#16]
Is it possible to add attributes to links in the team section? E.g., a `rel="me"` attribute to create verified links for Mastodon?

**Comment by raviriley** [comment]
Go ahead, if you'd like to customize any file in the theme simply override the file. For example, for the [team](https://github.com/raviriley/agency-jekyll-theme/blob/master/_includes/team.html) file, you would add the `_includes` folder and copy `team.html` into it, then update the attributes as desired.

**Comment by aosavi** [comment]
Great, thanks!
