### ISSUE TITLE
page 404

### ISSUE THREAD

**Issue by Jimmuy** [raviriley/agency-jekyll-theme-starter#3]
hello,after clicking the template button and named my project, I still cannot load my website  at MY-USERNAME.github.io，website show :

"404
File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages."

how can i fix it ,tks?

bty,i tried to set url and baseurl in _config.yml file ,but still not work

**Comment by raviriley** [comment]
Go to your repository, then click Settings. From there, click on the Pages tab. Make sure that the generated repo's GitHub Pages deployment is being built from your master branch.

**Comment by Jimmuy** [comment]
> Go to your repository, then click Settings. From there, click on the Pages tab. Make sure that the generated repo's GitHub Pages deployment is being built from your master branch.

it works，tks
