### ISSUE TITLE
Custom domain

### ISSUE THREAD

**Issue by robins-spark** [raviriley/agency-jekyll-theme-starter#8]
Hi, I'm trying to setup this theme with a custom domain.  It works when I build & serve locally but when I put it on github pages I get a 404 when going to the site.  I'd appreciate it if you could add configuration instructions for using your own domain name.

**Comment by rbenitezpagan** [comment]
@robins-spark How are you deploying your project?

**Comment by robins-spark** [comment]
I fixed it.  I was missing the CNAME file.  Still, I think it might be good to mention custom domains in the README since it discusses using YOUR-USERNAME.github.io and https://raviriley.github.io/agency-jekyll-theme-starter/.  Using a custom domain is a third option.

**Comment by raviriley** [comment]
Updated the README @robins-spark  :)
